"""
DorkRaptor - Comprehensive Google Dork Database
300+ dorks organized by category for OSINT reconnaissance
"""

from typing import Dict, List


DORK_DATABASE: Dict[str, List[str]] = {
    "sensitive_files": [
        "site:{domain} ext:env",
        "site:{domain} ext:log",
        "site:{domain} ext:sql",
        "site:{domain} ext:bak",
        "site:{domain} ext:backup",
        "site:{domain} ext:old",
        "site:{domain} ext:orig",
        "site:{domain} ext:save",
        "site:{domain} ext:tmp",
        "site:{domain} ext:swp",
        "site:{domain} ext:ini",
        "site:{domain} ext:cfg",
        "site:{domain} ext:conf",
        "site:{domain} ext:config",
        "site:{domain} ext:yaml",
        "site:{domain} ext:yml",
        "site:{domain} ext:toml",
        "site:{domain} ext:properties",
        "site:{domain} ext:pem",
        "site:{domain} ext:key",
        "site:{domain} ext:p12",
        "site:{domain} ext:pfx",
        "site:{domain} ext:csr",
        "site:{domain} ext:crt",
        "site:{domain} ext:cer",
        "site:{domain} ext:der",
        "site:{domain} ext:htpasswd",
        "site:{domain} ext:htaccess",
        "site:{domain} ext:ovpn",
        "site:{domain} ext:ppk",
        "site:{domain} ext:rdp",
        "site:{domain} filetype:env",
        'site:{domain} "/.env"',
        'site:{domain} inurl:".env"',
        'site:{domain} inurl:".git"',
        "site:{domain} ext:git",
        "site:{domain} inurl:wp-config.php",
        "site:{domain} inurl:config.php",
        "site:{domain} inurl:settings.php",
        "site:{domain} inurl:database.php",
        "site:{domain} inurl:db.php",
        "site:{domain} inurl:connect.php",
        "site:{domain} inurl:configuration.php",
        "site:{domain} inurl:local.xml",
        "site:{domain} inurl:application.yml",
        "site:{domain} inurl:application.properties",
    ],

    "credentials": [
        'site:{domain} "password"',
        'site:{domain} "passwd"',
        'site:{domain} "api_key"',
        'site:{domain} "api key"',
        'site:{domain} "apikey"',
        'site:{domain} "secret_key"',
        'site:{domain} "secret key"',
        'site:{domain} "access_key"',
        'site:{domain} "access_token"',
        'site:{domain} "auth_token"',
        'site:{domain} "private_key"',
        'site:{domain} "client_secret"',
        'site:{domain} "aws_secret"',
        'site:{domain} "aws_access_key"',
        'site:{domain} "AKIA"',
        'site:{domain} "aws_access_key_id"',
        'site:{domain} "db_password"',
        'site:{domain} "database_password"',
        'site:{domain} "mysql_password"',
        'site:{domain} "POSTGRES_PASSWORD"',
        'site:{domain} "DB_PASS"',
        'site:{domain} "SMTP_PASSWORD"',
        'site:{domain} "mail_password"',
        'site:{domain} "FTP_PASSWORD"',
        'site:{domain} "ssh_key"',
        'site:{domain} "BEGIN RSA PRIVATE KEY"',
        'site:{domain} "BEGIN OPENSSH PRIVATE KEY"',
        'site:{domain} "BEGIN PGP PRIVATE KEY"',
        'site:{domain} "token" ext:json',
        'site:{domain} "credentials" ext:json',
        'site:{domain} "Authorization: Bearer"',
    ],

    "admin_panels": [
        "site:{domain} inurl:admin",
        "site:{domain} inurl:admin/",
        "site:{domain} inurl:/admin",
        "site:{domain} inurl:administrator",
        "site:{domain} inurl:adminpanel",
        "site:{domain} inurl:admin-panel",
        "site:{domain} inurl:cpanel",
        "site:{domain} inurl:controlpanel",
        "site:{domain} inurl:wp-admin",
        "site:{domain} inurl:wp-login",
        "site:{domain} inurl:backend",
        "site:{domain} inurl:backend/login",
        "site:{domain} inurl:manage",
        "site:{domain} inurl:management",
        "site:{domain} inurl:manager",
        "site:{domain} inurl:phpmyadmin",
        "site:{domain} inurl:pma",
        "site:{domain} inurl:adminer",
        "site:{domain} inurl:webmaster",
        "site:{domain} inurl:siteadmin",
        "site:{domain} inurl:superuser",
        "site:{domain} inurl:root",
        'site:{domain} intitle:"admin" inurl:login',
        'site:{domain} intitle:"admin panel"',
        'site:{domain} intitle:"administration"',
        'site:{domain} intitle:"control panel"',
        'site:{domain} intitle:"dashboard" inurl:admin',
        "site:{domain} inurl:cms",
        "site:{domain} inurl:cms/admin",
        "site:{domain} inurl:joomla/administrator",
        "site:{domain} inurl:Drupal/admin",
        "site:{domain} inurl:typo3",
    ],

    "login_pages": [
        "site:{domain} inurl:login",
        "site:{domain} inurl:signin",
        "site:{domain} inurl:sign-in",
        "site:{domain} inurl:sign_in",
        "site:{domain} inurl:auth",
        "site:{domain} inurl:authenticate",
        "site:{domain} inurl:portal",
        "site:{domain} inurl:dashboard",
        "site:{domain} inurl:account",
        "site:{domain} inurl:user/login",
        "site:{domain} inurl:accounts/login",
        "site:{domain} inurl:session/new",
        "site:{domain} inurl:sso",
        "site:{domain} inurl:saml",
        "site:{domain} inurl:oauth",
        "site:{domain} inurl:openid",
        'site:{domain} intitle:"login"',
        'site:{domain} intitle:"sign in"',
        'site:{domain} intitle:"member login"',
        'site:{domain} intitle:"secure login"',
    ],

    "directory_listings": [
        'site:{domain} intitle:"index of"',
        'site:{domain} intitle:"index of /"',
        'site:{domain} intitle:"Index of" "parent directory"',
        'site:{domain} intitle:"directory listing"',
        'site:{domain} intitle:"Apache2 Ubuntu Default Page"',
        'site:{domain} intitle:"Apache HTTP Server"',
        'site:{domain} intitle:"Nginx" "Welcome to nginx"',
        'site:{domain} intitle:"IIS Windows Server"',
        'site:{domain} intitle:"WampServer"',
        'site:{domain} intitle:"XAMPP"',
        'site:{domain} intitle:"Index of" inurl:backup',
        'site:{domain} intitle:"Index of" inurl:upload',
        'site:{domain} intitle:"Index of" inurl:files',
        'site:{domain} intitle:"Index of" inurl:logs',
        'site:{domain} intitle:"Index of" ext:log',
        'site:{domain} intitle:"Index of" ext:sql',
        'site:{domain} "parent directory" -xxx -html -htm -php',
        'site:{domain} "directory listing" "last modified"',
    ],

    "backup_files": [
        "site:{domain} ext:bak",
        "site:{domain} ext:backup",
        "site:{domain} ext:old",
        "site:{domain} ext:orig",
        "site:{domain} ext:tar",
        "site:{domain} ext:tar.gz",
        "site:{domain} ext:tgz",
        "site:{domain} ext:zip",
        "site:{domain} ext:rar",
        "site:{domain} ext:7z",
        "site:{domain} ext:gz",
        "site:{domain} ext:bz2",
        "site:{domain} inurl:backup",
        "site:{domain} inurl:backups",
        "site:{domain} inurl:bak",
        "site:{domain} inurl:dump",
        'site:{domain} intitle:"backup"',
        "site:{domain} inurl:archive",
        'site:{domain} "backup" ext:sql',
        'site:{domain} "dump" ext:sql',
    ],

    "database_dumps": [
        "site:{domain} ext:sql",
        "site:{domain} ext:sql.gz",
        "site:{domain} ext:sql.zip",
        "site:{domain} ext:db",
        "site:{domain} ext:sqlite",
        "site:{domain} ext:sqlite3",
        "site:{domain} ext:mdb",
        "site:{domain} ext:accdb",
        "site:{domain} ext:dbf",
        'site:{domain} "mysqldump"',
        'site:{domain} "CREATE TABLE"',
        'site:{domain} "INSERT INTO"',
        'site:{domain} "pg_dump"',
        'site:{domain} "database backup"',
        'site:{domain} "db backup"',
        "site:{domain} inurl:database ext:sql",
        "site:{domain} inurl:db ext:sql",
        "site:{domain} inurl:mysql ext:sql",
        "site:{domain} inurl:dump ext:sql",
    ],

    "config_files": [
        "site:{domain} ext:config",
        "site:{domain} ext:conf",
        "site:{domain} ext:cfg",
        "site:{domain} ext:ini",
        "site:{domain} ext:yaml",
        "site:{domain} ext:yml",
        "site:{domain} ext:xml inurl:config",
        "site:{domain} ext:json inurl:config",
        "site:{domain} inurl:web.config",
        "site:{domain} inurl:app.config",
        "site:{domain} inurl:applicationhost.config",
        "site:{domain} inurl:.htaccess",
        "site:{domain} inurl:nginx.conf",
        "site:{domain} inurl:httpd.conf",
        "site:{domain} inurl:apache.conf",
        "site:{domain} inurl:php.ini",
        "site:{domain} inurl:my.cnf",
        "site:{domain} inurl:redis.conf",
        "site:{domain} inurl:settings.ini",
        'site:{domain} "REMOTE_ADDR" ext:config',
        'site:{domain} "server" ext:json',
        'site:{domain} "database" ext:yml',
        'site:{domain} "host" "port" ext:yml',
    ],

    "documents": [
        "site:{domain} filetype:pdf",
        "site:{domain} filetype:doc",
        "site:{domain} filetype:docx",
        "site:{domain} filetype:xls",
        "site:{domain} filetype:xlsx",
        "site:{domain} filetype:ppt",
        "site:{domain} filetype:pptx",
        "site:{domain} filetype:csv",
        "site:{domain} filetype:txt",
        "site:{domain} filetype:odt",
        "site:{domain} filetype:ods",
        "site:{domain} filetype:odp",
        'site:{domain} filetype:pdf intitle:"confidential"',
        'site:{domain} filetype:pdf intitle:"internal"',
        'site:{domain} filetype:pdf intitle:"private"',
        'site:{domain} filetype:xls "email" "password"',
        'site:{domain} filetype:csv "email" "password"',
        'site:{domain} filetype:xlsx "password"',
        'site:{domain} filetype:doc "confidential"',
        'site:{domain} filetype:pdf "not for distribution"',
    ],

    "api_endpoints": [
        "site:{domain} inurl:api",
        "site:{domain} inurl:/api/",
        "site:{domain} inurl:api/v1",
        "site:{domain} inurl:api/v2",
        "site:{domain} inurl:api/v3",
        "site:{domain} inurl:swagger",
        "site:{domain} inurl:swagger-ui",
        "site:{domain} inurl:api-docs",
        "site:{domain} inurl:openapi",
        "site:{domain} inurl:graphql",
        "site:{domain} inurl:rest",
        "site:{domain} inurl:soap",
        "site:{domain} inurl:wsdl",
        "site:{domain} inurl:xmlrpc",
        "site:{domain} inurl:jsonrpc",
        "site:{domain} ext:json inurl:api",
        'site:{domain} "api" ext:yaml',
        'site:{domain} intitle:"swagger"',
        'site:{domain} intitle:"API documentation"',
        "site:{domain} inurl:endpoints",
        "site:{domain} inurl:webhook",
        "site:{domain} inurl:callback",
    ],

    "cloud_storage": [
        "site:s3.amazonaws.com {domain}",
        "site:blob.core.windows.net {domain}",
        "site:storage.googleapis.com {domain}",
        'site:s3.amazonaws.com inurl:"{domain}"',
        "{domain} s3.amazonaws.com",
        "{domain} s3 bucket",
        "{domain} aws s3",
        "{domain} azure storage",
        "{domain} google cloud storage",
        "site:{domain} inurl:s3",
        "site:{domain} inurl:bucket",
        "site:{domain} inurl:storage",
        "site:{domain} inurl:cdn",
        "site:{domain} inurl:cloudfront",
        'site:{domain} "AmazonS3"',
        'site:{domain} "cloudflare"',
    ],

    "error_pages": [
        'site:{domain} intitle:"error" inurl:error',
        'site:{domain} intitle:"404" "not found"',
        'site:{domain} intitle:"500" "internal server error"',
        'site:{domain} intitle:"PHP Error"',
        'site:{domain} intitle:"Parse error"',
        'site:{domain} intitle:"Warning:" "PHP"',
        'site:{domain} intitle:"Fatal error"',
        'site:{domain} intitle:"MySQL error"',
        'site:{domain} intitle:"Database error"',
        'site:{domain} "stack trace"',
        'site:{domain} "exception" ext:log',
        'site:{domain} inurl:error ext:log',
        'site:{domain} "error_log"',
        'site:{domain} intitle:"Debug"',
        'site:{domain} "debug mode"',
        'site:{domain} "development mode"',
    ],

    "development": [
        "site:{domain} inurl:dev",
        "site:{domain} inurl:development",
        "site:{domain} inurl:staging",
        "site:{domain} inurl:stage",
        "site:{domain} inurl:test",
        "site:{domain} inurl:testing",
        "site:{domain} inurl:beta",
        "site:{domain} inurl:sandbox",
        "site:{domain} inurl:internal",
        "site:{domain} inurl:temp",
        "site:{domain} inurl:demo",
        "site:{domain} inurl:preview",
        "site:{domain} inurl:uat",
        "site:{domain} inurl:qa",
        "site:{domain} inurl:preprod",
        "site:{domain} inurl:pre-prod",
        'site:{domain} intitle:"staging"',
        'site:{domain} intitle:"test environment"',
    ],

    "exposed_services": [
        "site:{domain} inurl:phpinfo",
        "site:{domain} inurl:phpinfo.php",
        "site:{domain} inurl:info.php",
        "site:{domain} inurl:test.php",
        "site:{domain} inurl:shell.php",
        "site:{domain} inurl:cmd.php",
        "site:{domain} inurl:eval.php",
        "site:{domain} inurl:webshell",
        "site:{domain} inurl:cgi-bin",
        "site:{domain} inurl:.DS_Store",
        "site:{domain} inurl:robots.txt",
        "site:{domain} inurl:sitemap.xml",
        "site:{domain} inurl:crossdomain.xml",
        "site:{domain} inurl:clientaccesspolicy.xml",
        "site:{domain} inurl:.well-known",
        "site:{domain} inurl:.git/HEAD",
        "site:{domain} inurl:.svn",
        "site:{domain} inurl:.hg",
    ],

    "network_devices": [
        'site:{domain} intitle:"router" inurl:login',
        'site:{domain} intitle:"firewall" inurl:login',
        'site:{domain} intitle:"VPN" inurl:login',
        'site:{domain} intitle:"network management"',
        'site:{domain} intitle:"Cisco"',
        'site:{domain} intitle:"Netgear"',
        'site:{domain} intitle:"camera" inurl:view',
        'site:{domain} intitle:"webcam"',
        'site:{domain} intitle:"Network Camera"',
        'site:{domain} intitle:"Live View"',
        "site:{domain} inurl:8080",
        "site:{domain} inurl:8443",
        "site:{domain} inurl:8888",
        "site:{domain} inurl:9000",
        "site:{domain} inurl:3000",
        "site:{domain} inurl:4000",
    ],
}


def get_all_dorks(domain: str) -> List[Dict]:
    """Generate all dorks for a domain with metadata"""
    all_dorks = []
    for category, dork_templates in DORK_DATABASE.items():
        for template in dork_templates:
            dork = template.replace("{domain}", domain)
            all_dorks.append({
                "query": dork,
                "category": category,
                "template": template,
            })
    return all_dorks


def get_dorks_by_category(domain: str, category: str) -> List[str]:
    """Get dorks for a specific category"""
    templates = DORK_DATABASE.get(category, [])
    return [t.replace("{domain}", domain) for t in templates]


def get_total_dork_count() -> int:
    return sum(len(v) for v in DORK_DATABASE.values())


GITHUB_DORKS = [
    '"{domain}" password',
    '"{domain}" api_key',
    '"{domain}" secret_key',
    '"{domain}" access_token',
    '"{domain}" auth_token',
    '"{domain}" private_key',
    '"{domain}" aws_access_key_id',
    '"{domain}" db_password',
    '"{domain}" database_url',
    '"{domain}" connection_string',
    '"{domain}" credentials',
    '"{domain}" config',
    '"{domain}" .env',
    '"{domain}" BEGIN RSA PRIVATE KEY',
    '"{domain}" SMTP_PASSWORD',
]

CLOUD_BUCKETS = [
    "{domain}.s3.amazonaws.com",
    "{domain}-backup.s3.amazonaws.com",
    "{domain}-data.s3.amazonaws.com",
    "{domain}-dev.s3.amazonaws.com",
    "{domain}-prod.s3.amazonaws.com",
    "{domain}-staging.s3.amazonaws.com",
    "{domain}-assets.s3.amazonaws.com",
    "{domain}-media.s3.amazonaws.com",
    "{domain}-static.s3.amazonaws.com",
    "{domain}-uploads.s3.amazonaws.com",
    "{domain}-files.s3.amazonaws.com",
    "{domain}-logs.s3.amazonaws.com",
    "{domain}-images.s3.amazonaws.com",
    "{domain}-cdn.s3.amazonaws.com",
    "{domain}-public.s3.amazonaws.com",
    "{domain}.blob.core.windows.net",
    "{domain}-backup.blob.core.windows.net",
    "storage.googleapis.com/{domain}",
    "{domain}.storage.googleapis.com",
]
